Snapshot ingestion procedure for CSI Unity Driver
dell/csm-docs pull request #1043
Opened 2024-03-27 14:15 UTC by HarishH-DELL

# Description
Snapshot ingestion procedure for CSI Unity Driver.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1206 |

# Checklist:

- [X] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [X] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2024-03-27 17:18 UTC, gallacher requested changes
Please address the same review comments here that were made in https://github.com/dell/csm-docs/pull/1042.

2024-03-29 04:33 UTC, HarishH-DELL commented
> Please address the same review comments here that were made in #1042.

addressed the comments

2024-03-29 06:53 UTC, rajendraindukuri submitted a review, later dismissed

2024-03-29 09:57 UTC, rajendraindukuri approved these changes

2024-03-29 09:58 UTC, rajkumar-palani approved these changes
lgtm

2024-03-29 12:34 UTC, merged