Updating multicluster support page for `CSI-PowerScale`
dell/csm-docs pull request #1048
Opened 2024-04-01 10:29 UTC by rishabhatdell

# Description
Adding a note for multicluster support in csi-powerscale

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2024-04-01 10:54 UTC, adarsh-dell commented on content/docs/csidriver/features/powerscale.md
> +> The 'clusterName' serves as a logical, unique identifier that should remain unchanged once it is included in the volume handle. Altering this identifier is not advisable, as it would result in the
How about this: _unique identifier for the array_

2024-04-02 18:42 UTC, gallacher requested changes
Missing GitHub issue associated with this chage.

2024-04-02 20:19 UTC, gallacher requested changes
Why is this targeted for main and not release-1.11.0?  A known issue for this can be added to main but the doc changes here should be added to release-1.11.0.

2024-04-03 08:02 UTC, adarsh-dell commented
Closing this PR, as suggested by @gallacher . This will be part of CSM 1.11.0.

2024-04-03 08:08 UTC, closed without merging