Fixing sample link
dell/csm-docs pull request #1132
Opened 2024-06-03 11:00 UTC by adarsh-dell

# Description
Fixing sample link

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1319|

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2024-06-03 11:01 UTC, rishabhatdell approved these changes

2024-06-03 11:05 UTC, shanmydell approved these changes

2024-06-03 11:05 UTC, shanmydell reviewed
Only link should be given from main not from branches

2024-06-03 11:06 UTC, shanmydell requested changes
Address comments

2024-06-03 11:12 UTC, adarsh-dell commented
> Address comments

Hi @shanmydell ,

Thank you for your feedback.

I understand that not all releases occur on the main GitHub branch. While I agree with your approach, I have a concern regarding stability. Tags or release branches are generally more stable and unlikely to change, unlike the main branch where changes are frequent. This stability is especially important when we provide hyperlinks to specific files or directories.

However, if you still believe we should point to the main branch, we can wait until the changes from the release branch are merged into the main branch.
Reason: Sample v2.10.1 is not available in main branch yet.

Please let me know your thoughts.

2024-06-03 11:14 UTC, shanmydell commented
@adarsh-dell : Please merge the changes to the main and update the same link here, thanks.

2024-06-13 10:18 UTC, adarsh-dell commented
Please don't merge this PR in main branch, As some of the references used in this PR are not merged in to csm-op's main branch.

2024-06-18 07:07 UTC, adarsh-dell commented
@shanmydell Can you please review this PR.
I have addressed the comment.
Thanks

2024-06-18 07:09 UTC, shanmydell approved these changes

2024-06-18 09:49 UTC, merged