Merge main
dell/csm-docs pull request #1173
Opened 2024-07-11 08:04 UTC by rishabhatdell

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2024-07-11 09:48 UTC, shanmydell commented on .github/CODEOWNERS
> +# Shefali Malhotra (shefali-malhotra)
there is two entries

2024-07-11 09:48 UTC, shanmydell requested changes
Pls address the comments

2024-07-11 09:49 UTC, shanmydell commented on content/docs/authorization/v1.x GA/Backup and Restore/rpm/_index.md
> +The CSM Authorization RPM is no longer actively maintained or supported. It will be deprecated in a future release. It is highly recommended that you use CSM Authorization Helm deployment or CSM Oper
@gallacher : Do we have a timeline for deprecation?

2024-07-11 09:50 UTC, shanmydell commented on content/docs/csidriver/release/powerflex.md
> +- [#1210 - [BUG]: Helm deployment of PowerFlex driver is failing](https://github.com/dell/csm/issues/1210)
29 and 30 line is repeated

2024-07-11 09:50 UTC, shanmydell commented on content/docs/csidriver/release/powerscale.md
> +- Support for Kubernetes alpha features like Volume Health Monitoring will not be available in Openshift environment as Openshift doesn't support enabling of alpha features for Production Grade clust
45 and 46 line is repeated

2024-07-11 10:02 UTC, rishabhatdell commented on content/docs/csidriver/release/powerscale.md
> +- Support for Kubernetes alpha features like Volume Health Monitoring will not be available in Openshift environment as Openshift doesn't support enabling of alpha features for Production Grade clust
fixed

2024-07-11 10:02 UTC, rishabhatdell commented on content/docs/csidriver/release/powerflex.md
> +- [#1210 - [BUG]: Helm deployment of PowerFlex driver is failing](https://github.com/dell/csm/issues/1210)
fixed

2024-07-11 10:02 UTC, rishabhatdell commented on .github/CODEOWNERS
> +# Shefali Malhotra (shefali-malhotra)
fixed

2024-07-12 07:06 UTC, AkshaySainiDell submitted a review, later dismissed
LGTM

2024-07-12 07:29 UTC, suryagupta4 approved these changes

2024-07-12 07:29 UTC, AkshaySainiDell approved these changes

2024-07-15 07:45 UTC, shanmydell approved these changes

2024-07-15 07:49 UTC, merged