[Work In Progress]Powerscale upgrade steps improvement
dell/csm-docs pull request #120
Opened 2021-12-30 10:07 UTC by randeepsharma

# Description
Improve documentation for operator upgrade and driver upgrade via operator

# GitHub Issues
List the GitHub issues impacted by this PR:
https://github.com/dell/csm/issues/127

| GitHub Issue # |
https://github.com/dell/csm/issues/127
| |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2022-01-13 11:32 UTC, rensyct submitted a review, later dismissed

2022-01-13 13:22 UTC, shanmydell requested changes
@randeepsharma : Please rebase the code with the branch

2022-01-17 08:59 UTC, bpjain2004 submitted a review, later dismissed

2022-01-20 12:56 UTC, shanmydell commented on content/docs/csidriver/upgradation/drivers/operator.md
> +This is usually on OpenShift Platforms where OLM manages the operator upgrade.
@randeepsharma : Requesting your inputs here

2022-01-20 13:30 UTC, shanmydell commented
@randeepsharma : There was a formatting issue, 
![image](https://user-images.githubusercontent.com/82038610/150348103-0ddde53d-3962-4198-8655-2029d4c8864e.png)
Is this format okay?

2022-01-21 04:38 UTC, randeepsharma commented
> @randeepsharma : There was a formatting issue, ![image](https://user-images.githubusercontent.com/82038610/150348563-afc72cdb-92b2-461f-8188-ab858cd43079.png)
> 
> Is this format okay?

Yes.

2022-01-21 05:09 UTC, randeepsharma commented on content/docs/csidriver/upgradation/drivers/operator.md
> +This is usually on OpenShift Platforms where OLM manages the operator upgrade.
removed this line based on discussion

2022-01-21 05:11 UTC, shanmydell approved these changes

2022-01-21 07:13 UTC, rensyct approved these changes

2022-01-21 09:26 UTC, merged