Update sdc versions powerflex.md
dell/csm-docs pull request #1256
Opened 2024-09-20 11:34 UTC by rishabhatdell

# Description
Updating SDC troubleshooting for OpenShift 4.16

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2024-09-20 16:00 UTC, shanmydell requested changes
Hi Rishab, 

can we get our upgrading operator section updated with this info

thanks

2024-10-03 18:01 UTC, adarsh-dell commented
@rishabhatdell Do we still need this PR?

2024-10-07 11:44 UTC, gallacher commented on content/docs/csidriver/troubleshooting/powerflex.md
> +| After installation vxflexos-node pods are in an `Init:CrashLoopBackOff` state in OpenShift 4.16 with error message: ```Back-off restarting failed container sdc in pod vxflexos-node``` on non-suppor
Add comma.

"After installation, vxflexos-node pods..."

2024-10-07 11:49 UTC, rishabhatdell commented
Closing this PR as the issue has been fixed in the CSM 1.11.1 release.

2024-10-07 11:49 UTC, closed without merging