Fix typos & better prometheus conf
dell/csm-docs pull request #132
Opened 2022-02-02 16:11 UTC by coulof

# Description
This PR fixes minor syntax issue, correct some filename references and give an improved Prometheus config (doesn't cancel kubernetes scrape metrics anymore).

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [x] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2022-02-03 15:10 UTC, tdawe commented
Can you create a branch off of `release-1.2` and then target the PR at that branch. Thanks

2022-02-10 05:30 UTC, shanmydell requested changes
Renaming a link needs, link reference to be updated for FAQ page

2022-02-10 08:11 UTC, coulof commented
@tdawe, I solved the conflicts with the `release-1.2` branch

@shanmydell, sorry I don't understand the comment. The link in the FAQ was broken due to the renaming of the title.

2022-02-14 12:18 UTC, shanmydell commented
@coulof : [How do I uninstall or disable a Container Storage Module?](#how-do-i-uninstall-or-a-disable-a-module) As you have renamed the text in the question , the link on the side also will be updated, we have to change the reference of link as well

2022-02-14 23:01 UTC, AronAtDell commented on content/docs/FAQ/_index.md
> +- [How do I uninstall or a disable a module?](#how-do-i-uninstall-or-a-disable-a-module)
remove "a" before "disable"

2022-02-14 23:03 UTC, AronAtDell commented on content/docs/authorization/_index.md
> +![CSM for Authorization Workflow](./design2.png "CSM for Authorization Workflow")
What is the change here?

2022-02-15 13:11 UTC, coulof commented on content/docs/authorization/_index.md
> +![CSM for Authorization Workflow](./design2.png "CSM for Authorization Workflow")
There was a trailing EOL

2022-02-15 13:21 UTC, coulof commented
> @coulof : [How do I uninstall or disable a Container Storage Module?](#how-do-i-uninstall-or-a-disable-a-module) As you have renamed the text in the question , the link on the side also will be updated, we have to change the reference of link as well

Actually, the title has been renamed before, I just updated the link. I can change it back to what it used to be if you prefer or maybe you can point to where should happen this other change.

2022-02-21 08:13 UTC, coulof commented
@tdawe  & @shanmydell, do you mind reviewing once again ?

Thanks !

2022-02-21 08:33 UTC, shanmydell submitted a review, later dismissed
LGTM

2022-02-21 08:35 UTC, shanmydell commented
> @tdawe & @shanmydell, do you mind reviewing once again ?
> 
> Thanks !

Done.

2022-02-23 07:34 UTC, maxan98 submitted a review, later dismissed

2022-02-23 08:33 UTC, shanmydell approved these changes

2022-02-23 12:45 UTC, tdawe approved these changes

2022-02-23 12:48 UTC, merged