Setup Main branch with CSM 1.13
dell/csm-docs pull request #1380
Opened 2024-11-15 18:45 UTC by anandrajak1

# Description

- Set up main branch for v1.13
   - Moved current, v1 and v2 folders from release-1.12 branch to this one as v1, v2 and v3.
   - Pointed csm-release versions to latest ones.
   - Cherry picked changes from some PRs that went into main branch touching v1,v2,v3.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1559|

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2024-11-15 18:52 UTC, santhoshatdell approved these changes

2024-11-20 14:02 UTC, shanmydell requested changes
v1 index should have message of not actively maintained

2024-11-20 15:59 UTC, shanmydell approved these changes

2024-11-20 16:16 UTC, gallacher approved these changes

2024-11-21 00:40 UTC, merged