replication hostAliases documented
dell/csm-docs pull request #140
Opened 2022-02-14 14:20 UTC by maxan98

# Description
Adds missing parts about hostAlises feature for replication that allows users to inject FQDN:IP entries into their controller's pods

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2022-02-15 11:04 UTC, walker2 approved these changes

2022-02-18 11:20 UTC, IliaRN approved these changes

2022-02-21 07:18 UTC, shanmydell requested changes

2022-02-21 07:18 UTC, shanmydell commented on content/docs/replication/deployment/configmap-secrets.md
> +> This can be achieved by using helm installation method. Refer to the [link](../insttallation#)
Link is broken , please correct it

2022-02-21 11:51 UTC, walker2 approved these changes

2022-02-21 11:51 UTC, IliaRN approved these changes

2022-02-21 12:37 UTC, shanmydell approved these changes

2022-02-21 12:50 UTC, merged