Update Resiliency documentation for pod affinity and kubelet failure
dell/csm-docs pull request #141
Opened 2022-02-15 19:54 UTC by alikdell

Update Resiliency documentation for pod affinity and kubelet failure

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| #https://github.com/dell/csm/issues/87
 #https://github.com/dell/csm/issues/165  |

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2022-02-17 21:29 UTC, shaynafinocchiaro submitted a review, later dismissed

2022-02-17 21:35 UTC, shaynafinocchiaro commented
LGTM but can you merge into the `release-1.2` branch instead of `main`?

2022-02-18 13:16 UTC, atye submitted a review, later dismissed

2022-02-18 13:19 UTC, shanmydell requested changes
it has to be release branch

2022-02-18 13:35 UTC, tdawe commented on content/docs/resiliency/_index.md
> +| Kubernetes    | 1.20, 1.21, 1.22 1.23 |
Remove 1.20 if we are only supporting n-2 releases

2022-02-18 15:47 UTC, atye approved these changes

2022-02-18 21:16 UTC, shaynafinocchiaro approved these changes

2022-02-21 15:41 UTC, atye approved these changes

2022-02-21 15:54 UTC, sharmilarama approved these changes

2022-02-21 16:25 UTC, merged

2022-02-22 04:51 UTC, shanmydell commented on content/docs/resiliency/_index.md
> -CSM for Authorization supports the following CSI drivers and versions.
Good catch