Documentation on standalone installer and version tag for csi unity driver
dell/csm-docs pull request #196
Opened 2022-04-21 16:14 UTC by karthikk92

# Description
Documentation on standalone installer and vtag for csi unity driver

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/243 |

# Checklist:

- [] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2022-04-22 08:52 UTC, shanmydell requested changes

2022-04-22 08:52 UTC, shanmydell commented on content/docs/csidriver/installation/helm/unity.md
> +   To install nightly or latest csi driver build using bash script use the bellow command:
below* typo

2022-04-26 06:01 UTC, shanmydell commented
@rajendraindukuri @karthikk92 : Pls get PR to closure

2022-04-26 13:59 UTC, karthikk92 commented on content/docs/csidriver/installation/helm/unity.md
> +   To install nightly or latest csi driver build using bash script use the bellow command:
Taken care

2022-04-26 13:59 UTC, karthikk92 commented
> @rajendraindukuri @karthikk92 : Pls get PR to closure

Taken care

2022-04-26 14:00 UTC, shanmydell approved these changes

2022-04-26 14:15 UTC, panigs7 approved these changes

2022-04-26 14:16 UTC, merged

2022-04-27 12:04 UTC, rensyct commented on content/docs/csidriver/installation/helm/unity.md
> +
@karthikk92 , I feel Point 8 can be more descriptive and can be same as Point No 4  in PR https://github.com/dell/csi-unity/pull/82/files