add param to values section
dell/csm-docs pull request #207
Opened 2022-05-02 14:00 UTC by JacobGros

# Description
Adds documentation for fsgroup in pflex 

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/256 |

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2022-05-02 21:22 UTC, abhi16394 submitted a review, later dismissed

2022-05-02 22:49 UTC, jooseppi-luna reviewed
Currently "Supported" is capitalized in the middle of a sentence, perhaps change to this:

Defines which FS Group policy mode to be used, supported modes are `None`, `File` and `ReadWriteOnceWithFSType`

Edit: also adjusting backticks so they don't include the "and".

2022-05-03 18:17 UTC, bharathsreekanth approved these changes

2022-05-04 08:20 UTC, shanmydell requested changes
Add the release notes update

2022-05-06 09:45 UTC, shanmydell commented
@JacobGros : Could we get this PR updated?

2022-05-09 08:05 UTC, shanmydell commented
@JacobGros : Operator changes are missing, apologies for missing out in earlier comment

2022-05-17 12:19 UTC, JacobGros commented
> @JacobGros : Operator changes are missing, apologies for missing out in earlier comment

Currently operator is not supported- will update this PR when support is added

2022-05-25 05:52 UTC, randeepsharma commented on content/docs/csidriver/installation/helm/powerflex.md
> +| fsGroupPolicy | Defines which FS Group policy mode to be used. Supported modes are`None, File, and ReadWriteOnceWithFSType.` | No | "ReadWriteOnceWithFSType" |
In the values file the default is File.
https://github.com/dell/csi-powerflex/blob/main/helm/csi-vxflexos/values.yaml#L80

2022-05-25 11:12 UTC, merged