Volume Migration documentation added
dell/csm-docs pull request #221
Opened 2022-05-20 12:24 UTC by walker2

# Description

- Changed supported versions to align with 1.3
- Added Volume Migration page

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/265 |
| https://github.com/dell/csm/issues/266 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [x] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2022-05-20 12:31 UTC, alinamullagalieva approved these changes

2022-05-22 10:43 UTC, shanmydell requested changes
The changes has to be maded in release notes, installation -> helm page as well

2022-05-24 05:08 UTC, nidtara commented on content/docs/csidriver/installation/helm/powermax.md
> +| enabled                  | A boolean that enables/disables replication feature. |  No      |   false   |
This should be "migration feature"

2022-05-24 05:12 UTC, nidtara commented on content/docs/replication/migrating-volumes.md
> +Newly created PV (`test-pv-to-powermax-replication` in our example) is available for consumption via static provisioning by any PVC that will request it.
Post migration, will we support other use-cases like volume expansion, snapshot creation?

2022-05-24 07:29 UTC, walker2 commented on content/docs/csidriver/installation/helm/powermax.md
> +| enabled                  | A boolean that enables/disables replication feature. |  No      |   false   |
Yes, thanks will change it

2022-05-24 10:32 UTC, maxan98 approved these changes

2022-05-24 11:29 UTC, boyamurthy submitted a review, later dismissed
LGTM.

2022-05-24 11:50 UTC, shanmydell approved these changes

2022-05-24 11:51 UTC, boyamurthy approved these changes

2022-05-24 11:51 UTC, merged