Updateing k8 1.25 support in PowerMax
dell/csm-docs pull request #358
Opened 2022-09-29 10:01 UTC by boyamurthy

Updating K8 1.25 support for PowerMax driver 

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/478 |

# Checklist:

- [X] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [X] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2022-09-29 10:03 UTC, delldubey approved these changes
lgtm

2022-09-29 11:04 UTC, delldubey requested changes

2022-09-29 11:04 UTC, delldubey commented on content/docs/replication/_index.md
> +| Kubernetes    | 1.22, 1.23, 1.24 | 1.22, 1.23, 1.24 | 1.22, 1.23, 1.24 |
The change was correct. I think the table talks about Powermax supporting replication on 1.25 cluster.

2022-09-30 07:27 UTC, delldubey approved these changes
lgtm

2022-09-30 09:12 UTC, shanmydell approved these changes

2022-09-30 09:13 UTC, merged