Replication doc changes for csm-558, 532 and 573
dell/csm-docs pull request #425
Opened 2022-12-15 19:31 UTC by santhoshatdell

# Description
Doc updates for supporting failback, reprotect and improvements for PowerScale replication.
Note: This PR will be merged to the release branch based on when the corresponding replication code PRs merge.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/558 |
| https://github.com/dell/csm/issues/532 |
| https://github.com/dell/csm/issues/573 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2022-12-15 21:06 UTC, lukeatdell approved these changes

2022-12-15 21:28 UTC, EmilyKatdell approved these changes

2022-12-19 11:32 UTC, shanmydell requested changes
Please update the version in release notes

2022-12-19 11:34 UTC, rajkumar-palani submitted a review, later dismissed

2022-12-19 11:34 UTC, rajkumar-palani commented on content/docs/replication/release/_index.md
> + - Reprotect and Failback functionality have been added for PowerScale storage arrays.
Add Link to CSM Issue here.

2023-01-03 11:00 UTC, shanmydell commented
@santhoshatdell : Could you please address the changes requested?

2023-01-05 21:36 UTC, ChristianAtDell submitted a review, later dismissed

2023-01-05 21:44 UTC, santhoshatdell commented
> @santhoshatdell : Could you please address the changes requested?

Done. Please review again.

2023-01-06 22:24 UTC, ChristianAtDell approved these changes

2023-01-09 15:43 UTC, gallacher approved these changes

2023-01-09 15:56 UTC, merged