Added replication module known issue
dell/csm-docs pull request #569
Opened 2023-04-13 18:49 UTC by santhoshatdell

# Description

- Added a known issue to CSM Replication module release notes.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/753 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2023-04-13 19:07 UTC, ChristianAtDell approved these changes

2023-04-13 20:05 UTC, harshaatdell approved these changes

2023-04-13 20:10 UTC, anandrajak1 approved these changes

2023-04-17 05:34 UTC, rajkumar-palani approved these changes
lgtm

2023-04-17 05:49 UTC, shanmydell requested changes
Why changes made to all the releases?

2023-04-17 14:53 UTC, santhoshatdell commented
> Why changes made to all the releases?

To let the customers know that the issue exists in which versions and when it is fixed. This is @gallacher's suggestion.

2023-04-17 18:28 UTC, gallacher approved these changes

2023-04-19 16:32 UTC, merged