Remove the 'test-' prefix in name, namespace in CSI Unity XT docs
dell/csm-docs pull request #626
Opened 2023-05-18 06:30 UTC by karthikk92

# Description
Remove the 'test-' prefix in name, namespace in CSI Unity XT docs

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/743 |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2023-05-18 14:58 UTC, rensyct requested changes
@kk3, please revert the changes made to files under v1, v2 and v3.. Your changes should be there only for files under docs

2023-05-19 06:18 UTC, karthikk92 commented
> @kk3, please revert the changes made to files under v1, v2 and v3.. Your changes should be there only for files under docs

taken care

2023-05-19 12:50 UTC, panigs7 approved these changes

2023-05-22 06:18 UTC, rajkumar-palani approved these changes
lgtm

2023-05-22 06:19 UTC, merged