Add observability Support for powerscale 9.5
dell/csm-docs pull request #633
Opened 2023-05-18 21:38 UTC by anandrajak1

# Description
Supported added for observability for powerscale 9.5  

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/743|

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?

2023-05-18 23:16 UTC, mjsdell requested changes
Please hold on this until 5/19

2023-05-19 09:03 UTC, rsedlock1958 approved these changes
No grammatical edits required

2023-05-19 10:55 UTC, santhoshatdell approved these changes

2023-05-22 06:49 UTC, rajkumar-palani requested changes
Pls wait, there is a thread going on whether OneFS 9.5 is in scope or not.

2023-05-22 08:50 UTC, closed without merging