static provisioning and ephemeral changes
dell/csm-docs pull request #65
Opened 2021-11-11 09:22 UTC by gilltaran

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2021-11-11 14:23 UTC, shanmydell requested changes
@gilltaran : It has to go to content/docs not content/v1 , it points to older version

2021-11-12 06:34 UTC, gilltaran commented
> @gilltaran : It has to go to content/docs not content/v1 , it points to older version

ok I will add in content/docs also . Need to correct it for previous releases also. Can we do that ?

2021-11-12 09:40 UTC, shanmydell commented
> > @gilltaran : It has to go to content/docs not content/v1 , it points to older version
> 
> ok I will add in content/docs also . Need to correct it for previous releases also. Can we do that ?

Yes you can

2021-11-12 09:41 UTC, shanmydell approved these changes

2021-11-12 11:32 UTC, ashish2207 approved these changes

2021-11-12 12:20 UTC, closed without merging