Csm installation wizard node selector issue
dell/csm-docs pull request #681
Opened 2023-06-16 12:17 UTC by niranjan-n1

# Description
This PR adds the option to enable taints and install pods on control-plane through Installation Wizard

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2023-06-16 13:30 UTC, samihan-dell approved these changes

2023-06-16 13:55 UTC, rsedlock1958 submitted a review, later dismissed

2023-06-19 09:50 UTC, prablr79 approved these changes

2023-06-19 12:13 UTC, gallacher requested changes
@niranjan-n1 - please provide the GitHub issue linked to this PR.  Please also provide a listing of the tests that have been executed.

2023-06-19 13:15 UTC, gallacher approved these changes

2023-06-20 05:52 UTC, merged