updated installation and release notes to indicate support
dell/csm-docs pull request #696
Opened 2023-06-23 18:56 UTC by mbasha-dell

# Description
Updated installation and release notes to indicate support

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [x] Did you add the examples wherever applicable?
- [x] Have you added high-resolution images?

2023-06-23 21:21 UTC, sharmilarama approved these changes

2023-06-23 21:25 UTC, hoppea2 approved these changes

2023-06-24 01:30 UTC, prablr79 approved these changes

2023-06-24 04:03 UTC, rajkumar-palani requested changes
@mbasha-dell Since Merge is not done to release branch, this is not merged with the Main PR. Please create another PR for Main Branch directly and close this PR.

2023-06-24 04:09 UTC, rajkumar-palani approved these changes

2023-06-24 04:10 UTC, rajkumar-palani approved these changes
Approving the changes and merging with main. please merge the release changes on time and make it available in the PR raised for Main.

2023-06-24 04:11 UTC, merged