remove-incorrect-section
dell/csm-docs pull request #718
Opened 2023-07-21 13:39 UTC by JacobGros

# Description
This section  was removed, but put back in by accident. This section reverts the mistake. 
# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2023-07-25 14:59 UTC, gallacher approved these changes

2023-08-02 13:17 UTC, chimanjain submitted a review, later dismissed

2023-08-10 09:47 UTC, shanmydell requested changes
Add the Github id in description

2023-09-04 14:12 UTC, JacobGros commented
added ID

2023-09-04 16:29 UTC, shanmydell approved these changes

2023-09-05 13:18 UTC, sharont58 approved these changes

2023-09-05 13:33 UTC, merged