Volume limits support for CSI Powerstore
dell/csm-docs pull request #723
Opened 2023-07-25 17:37 UTC by alankar-verma

# Description
Support for volume limits feature in CSI Powerstore driver. The feature can be used either by setting :

- maxPowerstoreVolumesPerNode in values.yaml
- setting node label "max-powerstore-volumes-per-node"

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/878|

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [x] Have you tested whether the hyperlinks are working properly?
- [x] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2023-07-25 17:46 UTC, rsedlock1958 commented on content/docs/csidriver/features/powerstore.md
> +>**NOTE:** <br>The default value of `maxPowerstoreVolumesPerNode` is 0. <br>If `maxPowerstoreVolumesPerNode` is set to zero, then CO shall decide how many volumes of this type can be published by the
Insert "the" after "specified in"

2023-07-25 17:48 UTC, rsedlock1958 commented on content/docs/csidriver/installation/helm/powerstore.md
> +| maxPowerstoreVolumesPerNode | Defines the default value for maximum number of volumes that the controller can publish to the node. If the value is zero, then CO SHALL decide how many volumes of thi
Make SHALL lower case

2023-07-25 17:51 UTC, rsedlock1958 requested changes
Make changes as noted

2023-07-26 11:01 UTC, alankar-verma commented
> Make changes as noted

Made the required changes

2023-08-02 11:22 UTC, suryagupta4 commented on content/docs/csidriver/features/powerstore.md
> +The user can also set the volume limit for all the nodes in the cluster by specifying the same to `maxPowerstoreVolumesPerNode` attribute in values.yaml.
@alankar-verma Also mention here how to set the volume limit in case of driver installed via operator.

2023-08-16 05:50 UTC, suryagupta4 commented
@alankar-verma 
Add the env in the sample CR as well in case of operator.
file: content/docs/csidriver/installation/operator/powerstore.md

2023-08-25 09:26 UTC, alankar-verma commented
Closing this PR as target branch should be release-1.8.0 instead of main. Created a new PR https://github.com/dell/csm-docs/pull/782

2023-08-25 09:26 UTC, closed without merging