Updated the resiliency module for Powerstore operator support in Installation Wizard UI
dell/csm-docs pull request #745
Opened 2023-08-09 11:35 UTC by chaganti-rajitha

# Description
This PR is to update and fix the defect raised for resiliency module in PowerStore driver operator support.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| (https://github.com/dell/csm/issues/885) |
| https://jira.cec.lab.emc.com/browse/KRV-16403|

# Checklist:

- [X] Have you run a grammar and spell checks against your submission?
- [X] Have you tested the changes locally?
- [X] Have you tested whether the hyperlinks are working properly?
- [X] Did you add the examples wherever applicable?
- [X] Have you added high-resolution images?

2023-08-09 12:25 UTC, niranjan-n1 commented on content/docs/deployment/csminstallationwizard/src/index.html
> +                          <input class="form-control input-lg" type="number" id="array-threshold" placeholder="3" oninput="validateInput(validateForm, CONSTANTS)" required>
Set the min value as 3 if it should not be reduced below 3

2023-08-09 12:33 UTC, niranjan-n1 requested changes
Minor change requested

2023-08-09 12:43 UTC, samihan-dell approved these changes

2023-08-09 12:59 UTC, sharont58 commented on content/docs/deployment/csminstallationwizard/src/index.html
> +                        <label for="array-threshold" class="col-sm-3 col-form-label" data-bs-toggle="tooltip" data-bs-placement="right" title="Gives the number of failed connection polls that will be
Gives the number of failed connection polls that will indicate array connectivity loss.

(remove "deemed to")

2023-08-09 13:00 UTC, sharont58 requested changes
One comment

2023-08-09 13:37 UTC, sharont58 submitted a review, later dismissed

2023-08-09 14:14 UTC, samihan-dell approved these changes

2023-08-10 05:08 UTC, niranjan-n1 approved these changes

2023-08-10 05:32 UTC, suryagupta4 approved these changes

2023-08-10 06:08 UTC, shanmydell approved these changes

2023-08-10 06:08 UTC, merged