Added example of few suites
dell/csm-docs pull request #746
Opened 2023-08-10 04:12 UTC by adarsh-dell

# Description
Added example of ephemeral suite since for performance test --attr arg's value type have been modified to keep it consistent with the functional suite. Changed the vol health metrics suite from functional-test to test since it was a typo.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/930|

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [x] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?
![image](https://github.com/dell/csm-docs/assets/109620911/4ebad250-ab41-4f4f-975f-5ecb4a1ec019)

2023-08-10 13:00 UTC, sharont58 commented on content/docs/csidriver/installation/test/certcsi.md
> +To run volume health metric test suite, run the command:
To run **the** volume ...

2023-08-10 13:01 UTC, sharont58 commented on content/docs/csidriver/installation/test/certcsi.md
> +> Note: Make sure to enable healthMonitor for driver's controller and node pods before running this suite. It is recommended to use a smaller interval time for this sidecar.
... for **the** driver's ...

2023-08-10 13:01 UTC, sharont58 commented on content/docs/csidriver/installation/test/certcsi.md
> +To run ephemeral volume test suite, run the command:
To run **the** ephemeral ...

2023-08-10 13:06 UTC, sharont58 commented on content/docs/csidriver/installation/test/certcsi.md
> +--pods : Number of pods to create
In a list like this, use a parallel structure for each item: 
-pods : Number of pods to create 
--pod-name : Custom name for the pod
--attr : File name for the CSI volume attributes file
--fs-type: FS Type (optional)

2023-08-10 13:07 UTC, sharont58 commented on content/v1/csidriver/installation/test/certcsi.md
> +To run volume health metric test suite, run the command:
To run **the** volume health ...

2023-08-10 13:07 UTC, sharont58 commented on content/v1/csidriver/installation/test/certcsi.md
> +--pods : Number of pods to create
Same comment as above. Write each list item in the same style/format (parallel structure)

2023-08-10 13:07 UTC, sharont58 requested changes
See comments

2023-08-16 09:08 UTC, adarsh-dell commented on content/docs/csidriver/installation/test/certcsi.md
> +> Note: Make sure to enable healthMonitor for driver's controller and node pods before running this suite. It is recommended to use a smaller interval time for this sidecar.
Done @sharont58

2023-08-16 13:02 UTC, sharont58 approved these changes

2023-08-17 06:20 UTC, shanmydell approved these changes

2023-08-17 06:22 UTC, merged