remove incorrect line
dell/csm-docs pull request #770
Opened 2023-08-22 12:24 UTC by JacobGros

# Description
this PR removes an incorrect line found 
# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2023-08-22 13:09 UTC, sharont58 commented on content/docs/deployment/csmoperator/drivers/powerflex.md
> +   1. snapshotter and resizer sidecars are not optional to choose, it comes default with Driver installation.
Snapshotter and resizer sidecars installed by default.

2023-08-24 07:27 UTC, shanmydell requested changes
Implement the review comments

2023-09-04 14:12 UTC, JacobGros commented
> Implement the review comments

fixed wording

2023-09-05 13:36 UTC, sharont58 approved these changes

2023-09-06 14:51 UTC, rajkumar-palani approved these changes
lgtm

2023-09-06 15:05 UTC, shanmydell approved these changes

2023-09-06 15:06 UTC, merged