Merge release-1.7.1 changes into release-1.8.0
dell/csm-docs pull request #801
Opened 2023-08-31 04:21 UTC by VamsiSiddu-7

# Description
This pr adds the release-1.7.1 csm-docs changes into release-1.8.0

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/885  |

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2023-08-31 13:51 UTC, sharont58 commented on content/docs/csidriver/installation/helm/powerflex.md
> +After editing the file, run the below command to create a secret called `vxflexos-config`. This assumes `vxflexos` is release name, but it can be modified during [install](../#install-the-driver):
...run the command below ...

2023-08-31 13:53 UTC, sharont58 commented on content/docs/csidriver/installation/operator/powerflex.md
> +- If multipath is configured, ensure CSI-PowerFlex volumes are blacklisted by multipathd. See [troubleshooting section](../../../troubleshooting/powerflex) for details
...volumes are blocked ...

(See Dell's inclusive language terminology at https://dell.sharepoint.com/sites/InclusiveLanguage_DellTechnologies/SitePages/Documents/DOC-474277.aspx)

2023-08-31 13:55 UTC, sharont58 commented on content/v1/csidriver/installation/helm/powerflex.md
> +- If multipath is configured, ensure CSI-PowerFlex volumes are blacklisted by multipathd. See [troubleshooting section](../../../troubleshooting/powerflex/) for details
... volumes are excluded by ...

(Inclusive language)

2023-08-31 13:57 UTC, sharont58 commented on content/v3/csidriver/installation/helm/powerflex.md
> +- If multipath is configured, ensure CSI-PowerFlex volumes are blacklisted by multipathd. See [troubleshooting section](../../../troubleshooting/powerflex/) for details
... volumes are excluded from multipathd...

2023-08-31 13:59 UTC, sharont58 requested changes
See comments

2023-09-04 05:43 UTC, VamsiSiddu-7 commented
Closing this pr I will raise a new pr Thanks

2023-09-04 05:43 UTC, closed without merging