CSI 1.6 for CSI PowerScale and CSI Unity
dell/csm-docs pull request #861
Opened 2023-11-06 13:32 UTC by mdutka-dell

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] Have you run a grammar and spell checks against your submission?
- [ ] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [ ] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2023-11-07 11:26 UTC, shanmydell requested changes

2023-11-07 11:26 UTC, shanmydell commented on content/docs/csidriver/release/powerscale.md
> +| Storage capacity tracking does not return `MaximumVolumeSize` parameter. PowerScale is purely NFS based meaning it has no actual volumes. Therefore `MaximumVolumeSize` cannot be implemented if ther
Why Unity in PowerScale release notes?

2023-11-07 11:54 UTC, mdutka-dell commented on content/docs/csidriver/release/powerscale.md
> +| Storage capacity tracking does not return `MaximumVolumeSize` parameter. PowerScale is purely NFS based meaning it has no actual volumes. Therefore `MaximumVolumeSize` cannot be implemented if ther
mistake, thanks

2023-11-08 10:37 UTC, mareksuski-dell approved these changes
Looks good.

2023-11-08 12:22 UTC, rajkumar-palani requested changes
can you please check the comment?

2023-11-08 12:22 UTC, rajkumar-palani commented on content/docs/csidriver/_index.md
> +| Red Hat OpenShift | 4.12, 4.12 EUS, 4.13 | 4.12, 4.12 EUS, 4.13 | 4.12, 4.12 EUS, 4.13, 4.14 | 4.12, 4.12 EUS, 4.13, 4.14 | 4.12, 4.13, 4.13 EUS |
whether qualification is Completed on Open Shift 4.14 for Unity and PowerScale?

2023-11-09 09:39 UTC, rajkumar-palani approved these changes

2023-11-09 09:39 UTC, rajkumar-palani approved these changes
lgtm

2023-11-09 09:47 UTC, mareksuski-dell approved these changes
LGTM

2023-11-09 10:15 UTC, merged