Power-Path and Multi-Path Software guidance for PowerMax
dell/csm-docs pull request #869
Opened 2023-11-10 06:27 UTC by tssushma

# Description
The PowerPath and the multi-path software's should not be installed together, as Power-Path cannot co-exist with native multi-path software. Hence either of this should be installed.
Updating the documentation with this details.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1037|

# Checklist:

- [x] Have you run a grammar and spell checks against your submission?
- [x] Have you tested the changes locally?
- [ ] Have you tested whether the hyperlinks are working properly?
- [x] Did you add the examples wherever applicable?
- [ ] Have you added high-resolution images?

2023-11-10 06:33 UTC, boyamurthy approved these changes
LGTM.

2023-11-14 08:16 UTC, delldubey approved these changes
lgtm

2023-11-15 06:07 UTC, shanmydell requested changes
Please work on brand name

2023-11-15 06:21 UTC, tssushma commented
> Please work on brand name

@shanmydell Changed the brand name

2023-11-15 06:32 UTC, shanmydell approved these changes

2023-11-15 06:32 UTC, merged